// Generated by protocol/conformance/generate.py. Do not edit by hand.

use std::collections::BTreeMap;

use serde::{Deserialize, Serialize};

use crate::FunctionSchema;

pub const PROTOCOL_VERSION: u32 = 1;

#[derive(Clone, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct BridgeCapabilities {
    #[serde(default)]
    pub cancel: bool,
    #[serde(default)]
    pub events: bool,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum BridgeMessage {
    Hello {
        protocol_versions: Vec<u32>,
        sdk: String,
        sdk_version: String,
        token: String,
        #[serde(default)]
        capabilities: BridgeCapabilities,
    },
    HelloOk {
        protocol: u32,
        run_id: String,
        max_message_bytes: usize,
    },
    HelloError {
        code: String,
        message: String,
    },
    Describe {
        id: u64,
    },
    Schema {
        id: u64,
        protocol: u32,
        schema_hash: String,
        functions: BTreeMap<String, FunctionSchema>,
    },
    Call {
        id: u64,
        function: String,
        arguments: serde_json::Value,
        deadline_ms: u64,
    },
    Result {
        id: u64,
        value: serde_json::Value,
    },
    Error {
        id: u64,
        code: String,
        message: String,
        #[serde(default)]
        retryable: bool,
        #[serde(default)]
        data: serde_json::Value,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        debug: Option<String>,
    },
    Cancel {
        id: u64,
        reason: String,
    },
    Event {
        call_id: u64,
        kind: String,
        value: serde_json::Value,
    },
    Ping {
        id: u64,
    },
    Pong {
        id: u64,
    },
    Shutdown {
        id: u64,
    },
    ShutdownOk {
        id: u64,
    },
}
