// Generated by protocol/conformance/generate.py. Do not edit by hand.
export type Id = number;
export type Transferable = null | boolean | number | string | Transferable[] | { [key: string]: Transferable };
export type BridgeMessage =
  | { type: "hello"; protocol_versions: number[]; sdk: string; sdk_version: string; token: string; capabilities: { cancel: boolean; events: boolean } }
  | { type: "hello_ok"; protocol: 1; run_id: string; max_message_bytes: number }
  | { type: "hello_error"; code: string; message: string }
  | { type: "describe"; id: Id }
  | { type: "schema"; id: Id; protocol: 1; schema_hash: string; functions: Record<string, unknown> }
  | { type: "call"; id: Id; function: string; arguments: Record<string, Transferable>; deadline_ms: number }
  | { type: "result"; id: Id; value: Transferable }
  | { type: "error"; id: Id; code: string; message: string; retryable: boolean; data: Transferable; debug?: string }
  | { type: "cancel"; id: Id; reason: string }
  | { type: "event"; call_id: Id; kind: string; value: Transferable }
  | { type: "ping" | "pong" | "shutdown" | "shutdown_ok"; id: Id };
