[package]
name = "webtest"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "webtest"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
webtest-analysis.workspace = true
webtest-browser.workspace = true
webtest-browser-cdp.workspace = true
webtest-editor.workspace = true
webtest-format.workspace = true
webtest-lsp.workspace = true
webtest-observation.workspace = true
webtest-plan.workspace = true
webtest-runtime.workspace = true
webtest-syntax.workspace = true
webtest-text.workspace = true
