[package]
name = "webtest"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "webtest"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
clap.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
url.workspace = true
webtest-analysis.workspace = true
webtest-app-bridge = { path = "../app-bridge" }
webtest-browser.workspace = true
webtest-browser-cdp.workspace = true
webtest-browser-manager.workspace = true
webtest-dap.workspace = true
webtest-editor.workspace = true
webtest-format.workspace = true
webtest-feedback.workspace = true
webtest-lsp.workspace = true
webtest-model.workspace = true
webtest-observation.workspace = true
webtest-plan.workspace = true
webtest-provider.workspace = true
webtest-project.workspace = true
webtest-runtime.workspace = true
webtest-syntax.workspace = true
webtest-text.workspace = true

[dev-dependencies]
tempfile.workspace = true
