[package]
name = "webtest-provider"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
default = ["native"]
native = ["dep:libc", "dep:tempfile", "dep:tokio", "dep:ureq", "dep:url"]

[dependencies]
async-trait.workspace = true
blake3.workspace = true
libc = { workspace = true, optional = true }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tempfile = { workspace = true, optional = true }
tokio = { workspace = true, optional = true }
ureq = { workspace = true, optional = true }
url = { workspace = true, optional = true }
